services:
  - type: web
    name: minicook
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_MODEL
        value: openrouter/free
      - key: APP_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_VISION_MODEL
        sync: false
      - key: PREMIUM_CODE
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_MONTHLY
        sync: false
      - key: STRIPE_PRICE_QUARTERLY
        sync: false
      - key: STRIPE_PRICE_YEARLY
        sync: false
